apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  annotations:
    jenkins.io/last-build-number-for-master: "2"
  creationTimestamp: null
  labels:
    jenkins.io/chart-release: repos
    jenkins.io/namespace: jx
    jenkins.io/version: "51"
    owner: CognitiveScale
    provider: github
    repository: certifai-reference-models-jx
  name: cognitivescale-certifai-reference-models-jx
spec:
  description: Imported application for CognitiveScale/certifai-reference-models-jx
  httpCloneURL: https://github.com/CognitiveScale/certifai-reference-models-jx.git
  org: CognitiveScale
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: certifai-reference-models-jx
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/CognitiveScale/certifai-reference-models-jx.git
