apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: mvutapla-cs
    provider: github
    repository: node-http-demo
  name: mvutapla-cs-node-http-demo
spec:
  description: Imported application for mvutapla-cs/node-http-demo
  httpCloneURL: https://github.com/mvutapla-cs/node-http-demo.git
  org: mvutapla-cs
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: node-http-demo
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/mvutapla-cs/node-http-demo.git
